language: node_js

node_js:
    - "6"

cache:
    directories:
        - node_modules

install:
    - travis_retry npm install

before_script:
    - npm install -g gulp-cli coveralls

script:
    - gulp lint
    - gulp coverage

after_success:
    - cat ./coverage/lcov.info | coveralls
