language: node_js

node_js:
    - "6"

cache:
    directories:
        - node_modules

install:
    - travis_retry npm install

before_script:
    - npm install -g gulp-cli

script:
    - gulp coverage
    #- coveralls
